services:
    mongodb:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes: 
            - mongo-db:/data/db
    web:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - .:/app
            - /app/node_modules        
        environment: 
            - NODE_ENV=development
            - MONGO_USER=admin
            - MONGO_PASSWORD=password
            - MONGO_PORT=27017 
            - SESSION_SECRET=jkuhYDHBFIUEJN7492UEADSHNNASBAShdhsfhsdfh
            - REDIS_PORT=6379
        command: npm run dev